### ISSUE TITLE
Warnings in log-file

### ISSUE THREAD

**Issue by ckuratle** [unltdnetworx/ioBroker.stiebel-isg#50] opened 2021-07-27 15:15 UTC
**Describe the bug** 
toe log-file shows several warnings and info
2021-07-27 14:12:44.191 - info: stiebel-isg.0 (4612) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.WARMWASSERENERGIE.SO.WARMWASSERENERGIE_LINE" has to be type "number" but received type "string"
--
2021-07-27 14:12:44.192 - info: stiebel-isg.0 (4612) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.WARMWASSERENERGIE.LATEST_VALUE.WARMWASSERENERGIE_LINE" has to be type "number" but received type "string"
2021-07-27 14:12:44.192 - info: stiebel-isg.0 (4612) State value to set for "stiebel-isg.0.Info.ANLAGE.STATISTIK.WARMWASSERENERGIE.MO.WARMWASSERENERGIE_LINE" has to be type "number" but received type "string"
2021-07-27 14:12:44.193 - warn: stiebel-isg.0 (4612) State value to set for "stiebel-isg.0.Start.val1" has value "5" greater than max ""
2021-07-27 14:12:48.177 - warn: stiebel-isg.0 (4612) State value to set for "stiebel-isg.0.Einstellungen.HEIZEN.GRUNDEINSTELLUNG.val107" has value "1" greater than max ""
2021-07-27 14:12:48.180 - warn: stiebel-isg.0 (4612) State value to set for "stiebel-isg.0.Einstellungen.HEIZEN.GRUNDEINSTELLUNG.val35" has value "3686.4" greater than max "50"

Values shown in objects:

val1 | Betriebsart | state | level |   |   | WARMWASSERBETRIEB(5)
stiebel-isg.0.Einstellungen.HEIZEN.GRUNDEINSTELLUNG.val107 AUS(1)
stiebel-isg.0.Einstellungen.HEIZEN.GRUNDEINSTELLUNG.val35 3686.4

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
no warnings in log

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.6.0
 - JS-Controller version: <js-controller-version> 
 - Node version: v12.22.3 
 - Operating system: Windows10

**Additional context**

**Comment by unltdnetworx** [comment] 2021-07-27 15:20
Please try to update to the latest version with the github-cat and report, if the problem is fixed.
Then we can put this version to latest.

**Comment by ckuratle** [comment] 2021-07-27 15:29
I'm using the latest, stable version 1.6.0

**Comment by unltdnetworx** [comment] 2021-07-28 12:25
It is already fixed in the version on Github (1.7.2), as I said.
Stable version will be there soon.

**Closed by unltdnetworx** 2021-07-28 12:25 UTC
