### ISSUE TITLE
No values under "Info > WAERMEPUMPE"

### ISSUE THREAD

**Issue by Kunibert-007** [unltdnetworx/ioBroker.stiebel-isg#23] opened 2020-03-06 08:02 UTC
Since round about 1 or 2 weeks the adapter can`t read and write all values under "Info" and then "WAERMEPUMPE". So I don't get the values for used energy. All other values are available.
I guess the ISG made an automatic Update. My ISG-Version is 10.2.
When I use the display of the heating pump I get the informations.

![image](https://user-images.githubusercontent.com/35669927/76063779-aa905c80-5f88-11ea-9059-0bde248e4c82.png)

**Comment by unltdnetworx** [comment] 2020-03-06 08:13
Yes, I have a similiar issue since my update to 10.1.0 from 10.0.1. All my "Warmwasser"-values are gone. I'm in contact with Stiebel-Eltron. I think this is a bigger problem, but not with the adapter.

You can follow the discussion in the ioBroker forum. [Thread](https://forum.iobroker.net/topic/26210/test-adapter-stiebel-isg-v1-4-x-github)

**Comment by FraatRamski** [comment] 2020-10-16 11:53
Hello, I have the same issue since automatic update to ISG 11.1.0
![2020-10-16_13h51_38](https://user-images.githubusercontent.com/21004642/96255267-e8da0980-0fb6-11eb-9442-5ed6a7d9c6f3.png)

![2020-10-16_13h47_57](https://user-images.githubusercontent.com/21004642/96254904-5b96b500-0fb6-11eb-8c2f-426c525ef99b.png)

If I'm looking to the ISG himslef I can see the values.
![2020-10-16_13h51_38](https://user-images.githubusercontent.com/21004642/96255267-e8da0980-0fb6-11eb-9442-5ed6a7d9c6f3.png)

**Comment by unltdnetworx** [comment] 2020-10-25 11:11
Can you provide me the html-code for this site of the web interface, as I can not reproduce this error and probably won't update my system.

**Comment by FraatRamski** [comment] 2020-10-27 18:16
Hallo,

I have created an new instance of the adapter. In the new instance of the adapter is able to pull the values. 

![2020-10-27_19h11_22](https://user-images.githubusercontent.com/21004642/97343872-51af6480-1888-11eb-9bf0-b3ac0c1bb9c8.png)

**Comment by unltdnetworx** [comment] 2020-10-27 18:23
Perfect, so I can close this issue.

**Closed by unltdnetworx** 2020-10-27 18:23 UTC
